"""empty message

Revision ID: 230f0fc9a4fa
Revises: c4642f93b409
Create Date: 2020-06-19 21:55:15.777762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230f0fc9a4fa'
down_revision = 'c4642f93b409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_artist_id_key', 'Show', type_='unique')
    op.drop_constraint('Show_venue_id_key', 'Show', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Show_venue_id_key', 'Show', ['venue_id'])
    op.create_unique_constraint('Show_artist_id_key', 'Show', ['artist_id'])
    # ### end Alembic commands ###
