"""empty message

Revision ID: 31849be73285
Revises: 230f0fc9a4fa
Create Date: 2020-06-19 22:52:32.663154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31849be73285'
down_revision = '230f0fc9a4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Venue_Show',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'show_id')
    )
    op.drop_constraint('Show_venue_id_fkey', 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Show_venue_id_fkey', 'Show', 'Venue', ['venue_id'], ['id'])
    op.drop_table('Venue_Show')
    # ### end Alembic commands ###
