"""empty message

Revision ID: 69f4c8e0ca45
Revises: 015f8e44a32d
Create Date: 2020-06-19 11:39:42.674477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f4c8e0ca45'
down_revision = '015f8e44a32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genres_Venue')
    op.drop_table('Genres_Artists')
    op.drop_table('Genres')
    op.add_column('Artist', sa.Column('genres', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    op.create_table('Genres',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genres_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Genres_pkey'),
    sa.UniqueConstraint('genre', name='Genres_genre_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Genres_Artists',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='Genres_Artists_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['Genres.id'], name='Genres_Artists_genre_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id', name='Genres_Artists_pkey')
    )
    op.create_table('Genres_Venue',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genres.id'], name='Genres_Venue_genre_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='Genres_Venue_venue_id_fkey'),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id', name='Genres_Venue_pkey')
    )
    # ### end Alembic commands ###
