"""empty message

Revision ID: d7381e6d87de
Revises: 8911fe9db62b
Create Date: 2020-06-19 20:22:20.159594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7381e6d87de'
down_revision = '8911fe9db62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
